// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNWMm655V2kcH0D3i8_CPHg4Rw3vvi8n0',
    appId: '1:302417839036:web:d676ef014dfd3bd6d961b9',
    messagingSenderId: '302417839036',
    projectId: 'flutter-multiplatform-uyekaydi',
    authDomain: 'flutter-multiplatform-uyekaydi.firebaseapp.com',
    storageBucket: 'flutter-multiplatform-uyekaydi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzqVt0Qz9iG3ERAkc0UfrZrFA9QOw6p5o',
    appId: '1:302417839036:android:6434ac1092783738d961b9',
    messagingSenderId: '302417839036',
    projectId: 'flutter-multiplatform-uyekaydi',
    storageBucket: 'flutter-multiplatform-uyekaydi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6KH5KiNgbRCcyWHEff6amIKdhyxIlcNw',
    appId: '1:302417839036:ios:42b41c229ed5cd42d961b9',
    messagingSenderId: '302417839036',
    projectId: 'flutter-multiplatform-uyekaydi',
    storageBucket: 'flutter-multiplatform-uyekaydi.firebasestorage.app',
    iosBundleId: 'com.example.ilkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6KH5KiNgbRCcyWHEff6amIKdhyxIlcNw',
    appId: '1:302417839036:ios:42b41c229ed5cd42d961b9',
    messagingSenderId: '302417839036',
    projectId: 'flutter-multiplatform-uyekaydi',
    storageBucket: 'flutter-multiplatform-uyekaydi.firebasestorage.app',
    iosBundleId: 'com.example.ilkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNWMm655V2kcH0D3i8_CPHg4Rw3vvi8n0',
    appId: '1:302417839036:web:035def4e904dce1dd961b9',
    messagingSenderId: '302417839036',
    projectId: 'flutter-multiplatform-uyekaydi',
    authDomain: 'flutter-multiplatform-uyekaydi.firebaseapp.com',
    storageBucket: 'flutter-multiplatform-uyekaydi.firebasestorage.app',
  );

}